---
Name: emailobfuscator
After:
  - requestprocessors
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Control\Director:
    properties:
      Middlewares:
        EmailObfuscatorMiddleware: '%$Innoweb\EmailObfuscator\Middleware\EmailObfuscatorMiddleware'

PageController:
  extensions:
    - Innoweb\EmailObfuscator\Extensions\PageControllerExtension  
  